/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as SiteIndexRouteImport } from './routes/_site.index'
import { Route as SiteTerminosRouteImport } from './routes/_site.terminos'
import { Route as SiteProyectosRouteImport } from './routes/_site.proyectos'
import { Route as SitePrivacyRouteImport } from './routes/_site.privacy'
import { Route as SiteContactoRouteImport } from './routes/_site.contacto'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteTerminosRoute = SiteTerminosRouteImport.update({
  id: '/terminos',
  path: '/terminos',
  getParentRoute: () => SiteRoute,
} as any)
const SiteProyectosRoute = SiteProyectosRouteImport.update({
  id: '/proyectos',
  path: '/proyectos',
  getParentRoute: () => SiteRoute,
} as any)
const SitePrivacyRoute = SitePrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => SiteRoute,
} as any)
const SiteContactoRoute = SiteContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => SiteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/contacto': typeof SiteContactoRoute
  '/privacy': typeof SitePrivacyRoute
  '/proyectos': typeof SiteProyectosRoute
  '/terminos': typeof SiteTerminosRoute
}
export interface FileRoutesByTo {
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/contacto': typeof SiteContactoRoute
  '/privacy': typeof SitePrivacyRoute
  '/proyectos': typeof SiteProyectosRoute
  '/terminos': typeof SiteTerminosRoute
  '/': typeof SiteIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_site': typeof SiteRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_site/contacto': typeof SiteContactoRoute
  '/_site/privacy': typeof SitePrivacyRoute
  '/_site/proyectos': typeof SiteProyectosRoute
  '/_site/terminos': typeof SiteTerminosRoute
  '/_site/': typeof SiteIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sitemap.xml'
    | '/contacto'
    | '/privacy'
    | '/proyectos'
    | '/terminos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sitemap.xml'
    | '/contacto'
    | '/privacy'
    | '/proyectos'
    | '/terminos'
    | '/'
  id:
    | '__root__'
    | '/_site'
    | '/sitemap.xml'
    | '/_site/contacto'
    | '/_site/privacy'
    | '/_site/proyectos'
    | '/_site/terminos'
    | '/_site/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SiteRoute: typeof SiteRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/terminos': {
      id: '/_site/terminos'
      path: '/terminos'
      fullPath: '/terminos'
      preLoaderRoute: typeof SiteTerminosRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/proyectos': {
      id: '/_site/proyectos'
      path: '/proyectos'
      fullPath: '/proyectos'
      preLoaderRoute: typeof SiteProyectosRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/privacy': {
      id: '/_site/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof SitePrivacyRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/contacto': {
      id: '/_site/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof SiteContactoRouteImport
      parentRoute: typeof SiteRoute
    }
  }
}

interface SiteRouteChildren {
  SiteContactoRoute: typeof SiteContactoRoute
  SitePrivacyRoute: typeof SitePrivacyRoute
  SiteProyectosRoute: typeof SiteProyectosRoute
  SiteTerminosRoute: typeof SiteTerminosRoute
  SiteIndexRoute: typeof SiteIndexRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteContactoRoute: SiteContactoRoute,
  SitePrivacyRoute: SitePrivacyRoute,
  SiteProyectosRoute: SiteProyectosRoute,
  SiteTerminosRoute: SiteTerminosRoute,
  SiteIndexRoute: SiteIndexRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SiteRoute: SiteRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
